# DONT TOUCH THIS 
config_version: 1

# enabling or disabling crops to be grown by dancing
crops_grow: false

# enabling or disabling trees to be grown by dancing
tree_grow: true

# range (1-10)
# 1 = 3x3
range: 1

# chance to grow tree (1-10)
tree_grow_chance: 2
